# config v1.0.3.0
# Jekyll configuration
name: Near Future Rovers (NFR)
logo: /img/HeroLogo_1920x1920.jpg
description: An Addon for <a href="https://www.kerbalspaceprogram.com" style="color: #8ebf42" target="_blank">Kerbal Space Program</a>.
theme: jekyll-theme-architect
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap